--- #YAML:1.0
name:               SMS-Send-DE-Sipgate
version:            0.01
abstract:           An SMS::Send driver for the sipgate.de service.
author:
    - Dominik Schulz <dominik.schulz@gauner.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Cookies:  0
    Test::More:     0
    XMLRPC::Lite:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
